# -*- coding: utf-8 -*-
"""Добро пожаловать в Colaboratory!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

from google.colab import files
uploaded = files.upload()

m = 100
X = 6 * np.random.rand(m, 1) - 5
y = 0.7 * X ** 2 + X + 3 + np.random.randn(m, 1)

plt.figure(figsize=(10, 6))
plt.scatter(X, y, color="blue", label="Дані")
plt.title("Початкові дані")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.show()

lin_reg = LinearRegression()
lin_reg.fit(X, y)
y_pred_linear = lin_reg.predict(X)

plt.figure(figsize=(10, 6))
plt.scatter(X, y, color="blue", label="Дані")
plt.plot(X, y_pred_linear, color="red", label="Лінійна регресія")
plt.title("Лінійна регресія")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.show()

# Polynomial Features Transformation
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X)

# Polynomial Regression Model
lin_reg_poly = LinearRegression()
lin_reg_poly.fit(X_poly, y)
y_pred_poly = lin_reg_poly.predict(X_poly)
X_sorted_indices = np.argsort(X.flatten())
X_sorted = X[X_sorted_indices]
y_pred_poly_sorted = y_pred_poly[X_sorted_indices]

plt.figure(figsize=(10, 6))
plt.scatter(X, y, color="blue", label="Дані")
plt.plot(X_sorted, y_pred_poly_sorted, color="green", label="Поліноміальна регресія")
plt.title("Поліноміальна регресія")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.show()

# Mean Squared Errors
mse_linear = mean_squared_error(y, y_pred_linear)
mse_poly = mean_squared_error(y, y_pred_poly)

# Output Results
print("Коефіцієнти лінійної регресії:")
print(f"Інтерцепт: {lin_reg.intercept_[0]}, Коефіцієнт: {lin_reg.coef_[0][0]}")
print(f"Середньоквадратична похибка (MSE) для лінійної регресії: {mse_linear:.4f}")

print("\nКоефіцієнти поліноміальної регресії:")
print(f"Інтерцепт: {lin_reg_poly.intercept_[0]}, Коефіцієнти: {lin_reg_poly.coef_}")
print(f"Середньоквадратична похибка (MSE) для поліноміальної регресії: {mse_poly:.4f}")